---
- name: Testing andrewrothstein.pkg_upgrade
  hosts: all
  tasks:
    - name: Testing (update-only)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
      vars:
        pkg_upgrade_update_only: true
    - name: Testing (default)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
